import { AppConfig } from "@/lib/types/config";

export const DEFAULT_CONFIG: AppConfig = {
  autoGenerateEvents: true,
  autoGenerateDaysAhead: 2,
  autoCleanupOldEvents: true,
  keepEventsDays: 30,
  defaultEventDuration: 60,
  weekStartsOn: 1,
  notificationsEnabled: true,
  defaultNotificationMinutes: 15,
  showGhostEvents: true,
  showCurrentTime: true,
};
