export interface AppConfig {
  autoGenerateEvents: boolean;
  autoGenerateDaysAhead: number; // Unused
  autoCleanupOldEvents: boolean;
  keepEventsDays: number;
  defaultEventDuration: number; //
  weekStartsOn: 0 | 1; 
  notificationsEnabled: boolean; // Soon
  defaultNotificationMinutes: number; // Soon
  showGhostEvents: boolean; //
  showCurrentTime: boolean; //
  lastEventJob?: string;
}
